ENGR00238882 recovery: add basic ubi support.
Add basic ubi support, rewrite the updatevolume,
not use system() to call anther process to make
this image simple, no needs to change make file.

suport ubifs default in recovery system.

Use blk_device to replace device variable for jb4.3 upgrade
fstab_rec used to replace the Volume structure in jb4.3

fix sabreauto_6q lollipop nand compile error.
be lack of cryptfs.h when compile lollipop nand on sabreauto_6q
fatal error: cryptfs.h: No such file or directory

fix the issue of lacking *.h after change mtd-utils.
The new libubi_open don't need the parameter.
delete ubi_node_type which check whether it is a ubi volume.
The new mtd-utils don't have ubi_node_type().
There are codes which check  ubi volume after ubi_node_type.

This patch call binary ubiupdatevol to do factory reset.
remove the redundant header file.

This commit merge with below commits:
454cafc ENGR00254281:add ubifs support in recovery
57f46c7 ENGR00272747 Use blk_device to replace device variable for jb4.3 upgrade
8432f2a MA-5899 fix sabreauto_6q lollipop nand compile error
212d147 MA-5998 fix the compile error when after the mtd-utils
95bbfeb MA-7218-2 [Android_imx6_auto]factoryreset:do factory reset with binay ubiupdatevol in recovery
9704bdf MA-7218-3 [Android_imx6_auto]factoryreset:do factory reset with binay ubiupdatevol in recovery

Change-Id: I3e1d572cc994f4ea01552b0fcc50193882a042dc
Signed-off-by: Zhang Jiejing <jiejing.zhang@freescale.com>
Signed-off-by: Lin Fuzhen <fuzhen.lin@freescale.com>
Signed-off-by: guoyin.chen <guoyin.chen@freescale.com>
Signed-off-by: zhang sanshan <b51434@freescale.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/483
Reviewed-by: zhang sanshan <sanshan.zhang@nxp.com>
Reviewed-by: guoyin.chen <guoyin.chen@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/829
Reviewed-by: Xiaowen Liu <xiaowen.liu@nxp.com>